"""Agregar trial_days a Plan

Revision ID: 101f6b805840
Revises: 0bcd7f82b90a
Create Date: 2025-10-10 10:07:21.794104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101f6b805840'
down_revision = '0bcd7f82b90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_plan_subscription')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('trial_days')

    op.create_table('_alembic_tmp_user_plan_subscription',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('starts_at', sa.NUMERIC(), nullable=False),
    sa.Column('ends_at', sa.NUMERIC(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('created_by_admin_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
