"""Add subscription fields

Revision ID: 8a419ab8929c
Revises: 0e6b0eec4a4b
Create Date: 2025-10-03 14:41:52.061506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a419ab8929c'
down_revision = '0e6b0eec4a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_auth_token_code'), ['code'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('subscription_start',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_end',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_payment_date',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('payment_proof_reviewed_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('payment_proof_reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('last_payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('subscription_end',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('subscription_start',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_token_code'))
        batch_op.alter_column('code',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
