"""add user verification & payment cols

Revision ID: 97972bb54241
Revises: 
Create Date: 2025-09-29 09:43:15.227533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97972bb54241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=24), nullable=False, server_default=sa.text("'TRIAL_ACTIVO'")))
        batch_op.add_column(sa.Column('payment_proof_submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('payment_proof_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('payment_reviewed_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_payment_reviewed_by_admin', 'user', ['payment_reviewed_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_payment_reviewed_by_admin', type_='foreignkey')
        batch_op.drop_column('payment_reviewed_by_admin_id')
        batch_op.drop_column('payment_reviewed_at')
        batch_op.drop_column('payment_proof_url')
        batch_op.drop_column('payment_proof_submitted_at')
        batch_op.drop_column('account_status')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('is_email_verified')
    # ### end Alembic commands ###