"""Add magic_link_url to AuthToken

Revision ID: a1fbd7718683
Revises: bd494f5b46b4
Create Date: 2025-10-11 21:40:59.923670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fbd7718683'
down_revision = 'bd494f5b46b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('magic_link_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_column('magic_link_url')

    # ### end Alembic commands ###
