"""Add reference_note to AuthToken

Revision ID: bd494f5b46b4
Revises: 101f6b805840
Create Date: 2025-10-11 19:52:21.397965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd494f5b46b4'
down_revision = '101f6b805840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_note', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_column('reference_note')

    # ### end Alembic commands ###
